### ISSUE TITLE
GitHub API is exceeding rate limit

### ISSUE THREAD

**Issue by futursolo** [visvirial/sccache-action#3]
Sometimes this [action](https://github.com/futursolo/stellation/actions/runs/3992921267/jobs/6849193495) would report:

`Error: 403 error making request get https://api.github.com/repos/mozilla/sccache/releases/latest: "rate limit exceeded"`

This can be mitigated by providing the run's API token to the action from `secrets.GITHUB_TOKEN`:
See: https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-github-actions

Example:

```yaml
  - uses: visvirial/sccache-action@v2
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
```

Would it be possible to provide an input that supports providing a GitHub token?
